import { getSection, saveSection } from './contentService';

// ─── Default content for every section of every managed page ─────────────────
export const SITE_DEFAULTS = {
  global: {
    infobar: {
      item1Label: 'ANNÉE',
      item1Value: '2025-2026',
      item2Label: 'CAP & BT',
      item2Value: '15 SEPTEMBRE 2025',
      item3Label: 'MODULAIRE',
      item3Value: '13 AVRIL 2026',
    },
  },
  home: {
    hero: {
      titleMain: "L'ÉCOLE RÉGIONALE AXÉE SUR",
      titleHighlight: "LES MÉTIERS DE L'ÉNERGIE",
      subtitle: "Rejoignez la révolution des énergies renouvelables et devenez un leader reconnu.",
      badge1: 'Accrédité',
      badge2: 'Experts',
      badge3: 'Modernes',
      cta1: 'Admission',
      cta2: 'Découvrir nos formations',
    },
    hero_media: {
      slideshowImage1: '',
      slideshowImage2: '',
      slideshowImage3: '',
      videoUrl: '',
    },
    stats: {
      formes: 1500,
      emploi: 1200,
      partners: 50,
      certifies: 6,
    },
    info_box: {
      title: 'FORMATIONS MODULAIRES',
      startDate: '13 AVRIL 2026',
      duration: '6 à 12 mois',
      recognition: 'Meilleur acteur de formation en énergie renouvelable',
    },
    story: {
      title: "Une Vision pour l'Afrique",
      quote: "Depuis 2019, formant les experts énergétiques africains.",
      text1: "CREFER est née en 2019 d'une vision claire, former des jeunes Africains aux métiers des énergies renouvelables. Fondée par EGENT TOGO, leader en solutions solaires, notre académie répond au besoin urgent de techniciens qualifiés.",
      text2: "Le manque de spécialistes en photovoltaïque a motivé notre création. Aujourd'hui, nous sommes la référence régionale, formant des leaders de l'énergie solaire et de l'électricité.",
    },
    story_media: {
      storyImageUrl: '',
      joinUsImageUrl: '',
    },
    programs: {
      p1Title: "Électricité d'Équipement",
      p1Desc: "Maîtrisez les techniques essentielles de l'électricité et devenez un professionnel reconnu dans le domaine des équipements électriques.",
      p1Duration: '3 ans',
      p1Diploma: "Diplôme d'État",
      p1Badge: 'Niveau 1',
      p1Feat1: 'Formations pratiques intensives',
      p1Feat2: 'Matériel moderne et équipé',
      p1Feat3: 'Stages professionnels inclus',
      p2Title: 'BT Électrotechnique',
      p2Desc: "Accédez à une formation de haut niveau en électrotechnique avec approche théorique et pratique pour les futurs techniciens supérieurs.",
      p2Duration: '2-3 ans',
      p2Diploma: "Diplôme d'État",
      p2Badge: 'Niveau 2',
      p2Feat1: 'Enseignement avancé',
      p2Feat2: "Projets de fin d'études",
      p2Feat3: 'Reconnaissance nationale',
      p3Title: 'Formation Modulaire',
      p3Desc: "Des formations flexibles et certifiantes pour acquérir des compétences spécifiques en énergie solaire et électricité, à votre rythme.",
      p3Duration: '6-12 mois',
      p3Diploma: 'Certificat & Attestation',
      p3Badge: 'Flexible',
      p3Feat1: 'Horaires flexibles',
      p3Feat2: 'Modules personnalisés',
      p3Feat3: 'Certifications reconnues',
    },
    why_us: {
      heading: 'Choisir le Leader de la Formation',
      description: "CREFER se consacre à offrir une formation de premier ordre en énergie solaire et en électricité. Nos programmes sont conçus pour doter les étudiants des connaissances et des compétences nécessaires pour exceller dans un secteur de l'énergie en constante évolution.",
      feat1Title: 'Programme Innovant',
      feat1Text: "Constamment mis à jour pour refléter les dernières avancées technologiques du secteur énergétique.",
      feat2Title: 'Experts Reconnus',
      feat2Text: "Apprenez des meilleurs spécialistes du secteur, passionnés par l'excellence éducative.",
      feat3Title: 'Recherche Active',
      feat3Text: "Participez à des projets innovants répondant à des défis énergétiques concrets.",
      feat4Title: 'Impact Global',
      feat4Text: "Contribuez à la transition énergétique mondiale et façonnez un avenir durable.",
    },
    partners: {
      logo1: '',
      logo2: '',
      logo3: '',
      logo4: '',
    },
    portes_ouvertes: {
      dateBadge: '13 Avril 2026',
      heading: 'Portes Ouvertes CREFER 2026',
      introText: "Vous souhaitez maîtriser les métiers d'avenir à CREFER ? Profitez de la deuxième fixée au 13 avril 2026.",
      location: "L'annexe, situé au bord des pavés de Totsi non loin de l'agence Yas",
      hours: 'Cours du jour et du soir disponibles',
      duration: '06 ou 12 mois',
      mainImage: '',
      spvTitle: 'SPV (Système Photovoltaïque)',
      spvTags: 'Électricité,Énergie solaire,Biogaz,Plomberie*,Froid climatisation*',
      sstTitle: 'SST (Système de Sécurité & Télécom)',
      sstTags: 'Réseau,Alarmes,Caméras surveillance,Antennes paraboliques',
    },
    testimonials: {
      t1Name: "MELA D'Kigma Solmba",
      t1Role: 'Alumni promotion 12',
      t1Quote: "C'est pas du fake, CREFER c'est du vrai. J'ai appris des choses que je n'aurais jamais apprises ailleurs. La formation est intense mais les résultats sont là.",
      t1Photo: '',
      t2Name: 'YAO Amivi Emefa',
      t2Role: 'Alumni promotion 8 / Social Specialist centrale solaire Blitta',
      t2Quote: "Je suis YAO Amivi Emefa, ancienne étudiante de la Promotion 8 de CREFER. Grâce à cette formation, j'ai décroché un poste de Social Specialist à la centrale solaire de Blitta. CREFER m'a donné les outils pour réussir.",
      t2Photo: '',
      t3Name: 'SOW Kerfala',
      t3Role: 'Étudiant Promotion 13',
      t3Quote: "Je suis Guinéen, au départ, j'étais venu pour une courte formation, mais la qualité de l'enseignement et l'ambiance à CREFER m'ont convaincu de rester pour le programme complet.",
      t3Photo: '',
    },
    join_cta: {
      heading: 'Prêt à nous Rejoindre ?',
      description: 'Transforme ta carrière avec CREFER. Rejoins une communauté de plus de 5000 experts formés et propulse ton avenir dans les énergies renouvelables.',
      successRate: '95%',
      successLabel: 'Taux de réussite',
      image: '',
    },
    about_section: {
      heading: 'Leader en Formation Énergies Durables',
      description: "Depuis bientôt 10 ans, CREFER forme les experts en énergies renouvelables qui façonnent l'avenir de l'Afrique.",
      feat1Title: 'Formation Qualifiante',
      feat1Text: "Programmes CAP, BT et modules spécialisés reconnus par l'État et les professionnels du secteur.",
      feat2Title: 'Expertise Reconnue',
      feat2Text: "Formateurs experts du secteur avec une expérience combinée de plus de 200 ans dans l'électricité et les énergies renouvelables.",
      feat3Title: 'Placement Assuré',
      feat3Text: "95% de nos diplômés trouvent un emploi dans les 3 mois suivant leur formation grâce à notre réseau de partenaires.",
    },
    cta_final: {
      heading: "Commence Ton Voyage Vers l'excellence",
      description: "Les places pour les sessions 2025-2026 sont limitées. Inscris-toi maintenant et rejoins la révolution des énergies durables.",
      phone: 'tel:+22822XXXXXX',
      phoneLinkText: 'Appelle-Nous',
    },
  },
  about: {
    hero: {
      badge: 'À propos',
      title: 'CREFER, PREMIÈRE ACADÉMIE RÉGIONALE',
      line1: "AXÉE SUR LES MÉTIERS D'",
      line1Highlight: 'ÉNERGIES',
      line2: 'AVEC SON SIÈGE À ',
      line2Highlight: 'LOMÉ-TOGO',
      ctaText: 'Découvrir nos formations',
      backgroundImage: '',
    },
    histoire: {
      heading: 'NOTRE HISTOIRE',
      quote: "\"DEPUIS 2019, NOUS FORMONS DES JEUNES PRÊTS À RELEVER LES DÉFIS ÉNERGÉTIQUES DE L'AFRIQUE.\"",
      text1: "CREFER doit son existence à EGENT TOGO, entreprise solaire expert près les cours et tribunaux du TOGO œuvrant dans la fourniture et la pose du système photovoltaïque et dans l'électricité générale.",
      text2: "Le manque des techniciens qualifiés spécialistes en système photovoltaïque est au centre de l'ouverture dudit centre.",
      image: '',
    },
    vision_mission: {
      visionTitle: 'NOTRE VISION',
      visionText1: "Rendre autonome la jeunesse Africaine au travers d'un métier professionnel pratique pour briser en partie la chaîne du chômage.",
      visionText2: "Former des ambassadeurs qualifiés aux métiers d'énergies qui puissent vulgariser le bon fonctionnement des installations solaires au travers de leur prestation.",
      missionTitle: 'NOTRE MISSION',
      missionText: "Offrir une formation de qualité, axée sur les compétences pratiques et les exigences du marché, afin de garantir à chaque apprenant une employabilité durable, une insertion professionnelle réussie et la capacité de créer de la valeur dans son environnement.",
      image1: '',
      image2: '',
    },
    valeurs: {
      heading: 'NOS VALEURS FONDAMENTALES',
      description: "Les principes qui guident notre engagement envers l'excellence pédagogique et le succès de nos apprenants",
      val1Title: 'Discipline',
      val1Desc: 'Nous formons des professionnels rigoureux, responsables et respectueux des standards du métier.',
      val2Title: 'Excellence',
      val2Desc: 'Nous accompagnons chaque apprenant vers le meilleur de lui-même, avec des formations de haute qualité.',
      val3Title: 'Professionnalisme',
      val3Desc: "Nous préparons des talents immédiatement opérationnels, capables de répondre efficacement aux exigences du marché.",
    },
    methode: {
      heading: 'NOTRE MÉTHODE',
      text1: 'Nous offrons une formation complète regroupant la phase théorique, travaux pratiques puis les stages professionnels en entreprise.',
      text2: "Nous disposons d'une division spéciale dédiée à l'insertion professionnelle des étudiants. Elle les accompagne également dans le développement de leurs projets entrepreneuriaux liés aux métiers de l'énergie.",
      point1: 'Phase théorique avancée',
      point2: 'Travaux pratiques intensifs',
      point3: 'Stages en entreprise',
      point4: 'Accompagnement entrepreneurial',
      image1: '',
      image2: '',
      image3: '',
      image4: '',
    },
    deux_sites: {
      heading: 'NOS DEUX SITES DE FORMATION',
      description: 'CREFER dispose de deux sites de formations distants de 800 mètres pour une meilleure accessibilité',
      site1Name: 'Le Siège',
      site1Desc: "Le siège principal de CREFER, accueille l'administration et les étudiants inscrits en formation modulaire",
      site1Addr: 'Totsi Gblenkome, Lomé',
      site1Image: '',
      site2Name: "L'Annexe",
      site2Desc: "Non loin de l'agence Yas, l'annexe accueille principalement les apprenants inscrits en CAP et BT",
      site2Addr: 'Près de Yas, Totsi',
      site2Image: '',
      distance: '800 mètres',
    },
    formation: {
      heading: 'UNE FORMATION COMPLÈTE ET DIVERSIFIÉE',
      description: 'Au-delà de la technique, nous formons des entrepreneurs et des leaders',
      card1Title: 'Formation Complète',
      card1Desc: "Outre les cours techniques, nos étudiants bénéficient de sessions sur le leadership et la création d'entreprise. Cette approche holistique vise à former des professionnels compétents et entrepreneurs.",
      card2Title: 'Diversité Énergétique',
      card2Desc: "Nos cours couvrent diverses énergies renouvelables, y compris le biogaz, avec des expériences pratiques basées sur des déchets organiques et cas réels.",
      card3Title: 'Deux Rentrées par an',
      card3Desc: "Nous offrons deux rentrées (Avril et Octobre) chaque année depuis plus de 5 ans. Une flexibilité accrue pour les étudiants avec diverses opportunités d'admission.",
    },
    distinctions: {
      heading: 'DISTINCTIONS ET COLLABORATIONS',
      description: "CREFER est honoré d'avoir reçu plusieurs distinctions au Togo et à l'international",
      d1Year: 'Décembre 2020',
      d1Text: "Meilleur acteur de formation au cours du Forum des Énergies Renouvelables & Emploi des Jeunes",
      d2Year: 'Novembre 2023',
      d2Text: "Meilleur Centre de Formation en Énergies Renouvelables au Gala Energy Awards, organisé dans le cadre de la foire des énergies renouvelables au Togo par la Synergie des Acteurs des Énergies Renouvelables (SAER TOGO)",
      d3Year: 'Décembre 2023',
      d3Text: "Meilleur acteur de l'éducation lors de la cérémonie du Grand Prix Général Mathieu KEREKOU à Cotonou",
      memberText: 'Membre actif de SAER-TOGO',
      collab1Title: 'Commission Consultation Sectorielle (CCS)',
      collab1Text: "CREFER est fière d'être membre de la CCS du CERME de l'université de Lomé. Nous collaborons étroitement pour garantir des programmes de qualité et actualisés.",
      image1: '',
      image2: '',
    },
    cta: {
      heading: 'Prêt à rejoindre CREFER ?',
      description: 'Découvrez nos programmes et devenez un expert en énergies renouvelables',
      btn1Text: 'Nos Admissions',
      btn2Text: 'Nous Contacter',
    },
  },
  programmes: {
    hero: {
      badge: 'Nos Formations',
      title: 'NOS PROGRAMMES DE FORMATIONS',
      description: "Découvrez l'ensemble de nos formations complètes : théorie, travaux pratiques, stages et accompagnement entrepreneurial.",
      backgroundImage: '',
    },
    intro: {
      heading: 'Notre Approche Pédagogique',
      text: 'Au CREFER, nous bâtissons des professionnels grâce à la discipline, la rigueur et un accompagnement constant.',
    },
    cap: {
      heading: "CAP Électricité d'Équipement",
      subtitle: 'Formation complète de 3 ans',
      qualifText: "Le CAP est un diplôme d'état, attestant une qualification professionnelle de base.",
      dureeText: "La formation s'étend sur trois (03) ans avec un niveau d'entrée minimum de la classe de quatrième.",
      objectifsText: "Former des ouvriers qualifiés capables d'exécuter des travaux d'installation et de maintenance des équipements électriques dans les bâtiments neuves ou en rénovation.",
      debouchesText: "Les titulaires peuvent exercer en tant qu'électriciens d'équipement, installateurs ou maintenanciers en électricité et poursuivre les études en Brevet de Technicien en électrotechnique.",
      entreeLabel: 'Entrée : Minimun la classe de quatrième (4ème)',
      entreeSub: 'Avec excellente motivation et connaissances scientifiques',
      dureeLabel: 'Durée : 3 ans',
      dureeSub: 'Rentrée : 15 Septembre 2025',
      image: '',
    },
    bt: {
      heading: 'BT Électrotechnique',
      subtitle: 'Formation de technicien supérieur',
      qualifText: "Le BT est un diplôme d'état équivalent au baccalauréat professionnel, attestant d'une qualification technique approfondie.",
      dureeText: "La formation dure deux à trois ans avec un niveau d'entrée minimum de BEPC ou un CAP en électricité d'équipement.",
      objectifsText: "Former des techniciens capables de concevoir, installer, gérer et maintenir des systèmes électrotechniques complexes, incluant la production, le transport, la distribution et l'utilisation de l'énergie électrique.",
      debouchesText: "Les diplômés peuvent occuper des postes de techniciens en électrotechnique, chefs de chantier en installations électriques, ou poursuivre leurs études vers un Brevet de Technicien Supérieur (BTS), Licence en électrotechnique.",
      entreeLabel: "Entrée : BEPC ou un CAP en électricité d'équipement",
      entreeSub: 'Avec excellente motivation et connaissances scientifiques',
      dureeLabel: 'Durée : 3 ans',
      dureeSub: 'Rentrée : 15 Septembre 2025',
      image: '',
    },
    modulaire: {
      heading: 'Formations Modulaires',
      subtitle: '2 filières à la carte flexibles',
      overviewText: "Nos formations modulaires (06 ou 12 mois) offrent une grande flexibilité et permettent aux apprenants de développer des compétences spécifiques de manière progressive et adaptée à leurs besoins. La formation est sanctionnée par un certificat et une attestation de stage. le choix se fait selon les moyens financiers de l'apprenant et sa disponibilité",
      conditionsText: "Un niveau d'entrée minimum de BEPC ou équivalent.",
      niveau1Title: 'Option Niveau 1 : 06 mois',
      niveau1Label: "Électricité d'Équipement & Énergie Solaire",
      niveau1Text: "Le diplômé est apte à réaliser et entretenir des installations électriques dans les bâtiments résidentiels et commerciaux. Il peut aussi dimensionner et installer des systèmes solaires domestiques. Il peut exercer à son propre compte comme patron électricien/technicien solaire ou être recruté dans une entreprise de BTP ou d'énergie.",
      niveau2Title: 'Option Niveau 2 : 12 mois',
      niveau2Label: "Électricité d'Équipement & Énergie Solaire",
      niveau2Text: "Le diplômé est capable d'installer et de dépanner des systèmes électriques dans les bâtiments et les usines. Il maîtrise aussi l'installation de systèmes solaires de plus grande capacité, le pompage solaire et la programmation d'onduleurs hybrides. Il peut exercer à son compte ou en entreprise (Industrie, BTP, solaire).",
      entreeLabel: 'Entrée : BEPC ou équivalent',
      entreeSub: 'Flexible selon votre profil et vos objectifs',
      dureeLabel: 'Durée : 6 ou 12 mois',
      dureeSub: 'Rentrée : 13 Avril 2026',
      image: '',
    },
    cta: {
      heading: 'Trouvez le programme qui vous convient',
      text: "Que vous soyez un étudiant à la recherche d'une formation complète, un professionnel souhaitant développer ses compétences, un fonctionnaire en quête de nouvelles aptitudes, ou encore en pleine reconversion, le CREFER a la solution pour vous.",
      btn1Text: "S'inscrire",
      btn2Text: "Plus d'infos",
    },
  },
  contact: {
    info: {
      address: 'Lomé, Togo - Quartier Agbalépédogan',
      email1: 'info@crefer.cm',
      email2: 'admissions@crefer.cm',
      phone1: '+228 90 XX XX XX',
      phone2: '+228 91 XX XX XX',
      hours: 'Lundi - Vendredi: 8h00 - 17h00',
    },
  },
  admissions: {
    hero: {
      badge: 'Admission 2025',
      title: 'RENTRÉE ACADÉMIQUE 2025-2026',
      capBtLabel: 'CAP & BT :',
      capBtDate: '15 SEPTEMBRE 2025',
      modulaireLabel: 'MODULAIRE :',
      modulaireDate: '13 AVRIL 2026',
      ctaText: 'Nous contacter',
      backgroundImage: '',
    },
    conditions: {
      heading: "Conditions d'Admission",
      capBtTitle: 'CAP & BT',
      cap1: "Être titulaire d'un diplôme BAC ou équivalent",
      cap2: 'Avoir une excellente motivation',
      cap3: 'Bonnes connaissances scientifiques',
      cap4: "Entretien d'admission requis",
      cap5: 'Frais de scolarité applicables',
      modulaireTitle: 'Formation Modulaire',
      mod1: 'Modules à la carte',
      mod2: 'Flexible et adaptatif',
      mod3: 'Pour professionnels en activité',
      mod4: 'Certifications partielles possibles',
      mod5: 'Tarifs réduits',
    },
    fiches: {
      heading: "Fiches d'Inscription & Documentation",
      infoText: "La fiche d'inscription peut être imprimée, remplie et déposée au secrétariat de CREFER. (Fiches d'inscription à télécharger ci-dessus)",
    },
    cta: {
      heading: 'PRÊT À NOUS REJOINDRE ?',
      description: "Faites un pas de plus vers votre carrière dans l'énergie solaire et l'électricité ! Découvrez nos programmes et postulez dès aujourd'hui.",
      buttonText: 'Inscrivez-vous',
      image: '',
    },
  },
};

// ─── Fetch a section, merge with defaults ────────────────────────────────────
export const getSiteSection = async (pageId, sectionId) => {
  const defaults = SITE_DEFAULTS[pageId]?.[sectionId] || {};
  try {
    const section = await getSection(pageId, sectionId);
    if (!section) {
      // Section does not exist yet in Firebase — expected on first use
      return { ...defaults };
    }
    return { ...defaults, ...(section.content || {}) };
  } catch (error) {
    // Firebase read failed (permission-denied, network, etc.) — data will appear reset
    console.warn(
      `[CMS] Échec lecture Firebase ${pageId}/${sectionId} (code: ${error?.code ?? error?.message}). ` +
      'Vérifiez les règles Firestore (lecture publique requise).'
    );
    return { ...defaults };
  }
};

// ─── Save a section ───────────────────────────────────────────────────────────
export const saveSiteSection = async (pageId, sectionId, content) => {
  return saveSection(pageId, sectionId, { name: sectionId, content });
};
